apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: testapp
  namespace: nais
  labels:
    team: aura
spec:
  image: docker.pkg.github.com/nais/up/up:latest
  port: 8080
  liveness:
    path: /
  readiness:
    path: /
  replicas:
    min: 2
    max: 4
  ingresses: 
{{#each ingresses}}
    - {{this}}
{{/each}}
  resources:
    limits:
      cpu: {{resources.limits.cpu}}
      memory: {{resources.limits.memory}}
    requests:
      cpu: {{resources.requests.cpu}}
      memory: {{resources.requests.memory}}
