apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: up
  namespace: nais-system
  labels:
    team: nais
spec:
  image: ghcr.io/nais/up/up:{{ .Values.imageTag }}
  port: 8080
  liveness:
    path: /
  readiness:
    path: /
  replicas:
    min: 2
    max: 4
  ingresses:
    {{- toYaml .Values.ingresses | nindent 4 }}
      {{- range .ingresses }}
        - {{ . }}
    {{- end }}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
